create table products(
	id varchar(10) NOT NULL,
	description text,
	unity varchar(2),
	categorie text,
	cost double default 0,
	sale_price_1 double default 0,
	observation text,
	provider text,
	stock int(6) unsigned default 0,
	barcode text,
	sale_price_2 double default 0,
	sale_price_3 double default 0,
	min_stock int(6) unsigned default 0,
	max_stock int(6) unsigned default 0,
	stock_purchase int(6) unsigned default 0,
	sales_unit_factor int(6) unsigned default 0,
	NCM text,
	mark text,
	weight int(6) unsigned default 0,
	size int(6) unsigned default 0,
	inactive tinyint(1),
	type int(6) unsigned,
	composition int(6) unsigned,
	feedstock int(6) unsigned,
	business_mateiral int(6) unsigned,
	for_sale int(6) unsigned,
	coin varchar(3),
	ipi double default 0,
    	gender text,
	PRIMARY KEY(id)
);
